// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckProxy(arg1) {
  return window['go']['utils']['Proxy']['CheckProxy'](arg1);
}
